In [4]:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ALEJANDRO MELGUIZO
# DATE: 8/18/2026
# TOPIC: Python version of csv_edit.R
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

import os
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk

In [2]:
os.chdir("C:/Users/A.Melguizo001/Downloads/Immig, Wages, Latinos")

In [ ]:
df_1 = pd.read_csv('econometrics_v_10.csv')
df_hisp = df_1.copy()

,YEAR,REGION,STATEFIP,AGE,SEX,RACE,BPL,YRIMMIG,CITIZEN,NATIVITY,...,bpl_binary,bpl_detail,nativity_clean,educ_clean,region_clean,sex_clean,citizen_clean,empstat_clean,incwage_clean,inctot_clean
0,2000,11,23,51,2,100,45300,1,3,5,...,1,4.0,5.0,4,1,1,1,1,44600.0,78644.000
1,2000,11,23,41,1,100,41400,3,4,5,...,1,4.0,5.0,2,1,0,2,1,37500.0,37525.000
2,2000,11,23,59,1,100,41100,3,4,5,...,1,4.0,5.0,0,1,0,2,1,23000.0,23025.000
3,2000,11,23,55,2,100,15000,3,4,5,...,1,0.0,5.0,1,1,1,2,1,4860.0,5009.000
4,2000,11,23,59,1,100,11000,5,2,5,...,0,0.0,5.0,2,1,0,1,1,44000.0,44000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415916,2025,42,15,58,2,651,51500,38,4,5,...,1,5.0,5.0,2,4,1,2,1,19647.0,20733.426
415917,2025,42,15,61,2,651,51500,7,4,5,...,1,5.0,5.0,1,4,1,2,1,29736.0,29736.000
415918,2025,42,15,36,2,651,50000,41,5,5,...,1,5.0,5.0,2,4,1,0,1,8549.1,8549.631
415919,2025,42,15,55,2,651,51500,9,4,5,...,1,5.0,5.0,2,4,1,2,3,0.0,19010.331
415920,2025,42,15,57,1,652,10000,11,2,5,...,0,0.0,5.0,3,4,0,1,3,0.0,29433.861

In [ ]:
#filter to only include hispanic respondents
df_hisp_MA = df_hisp[df_hisp['hisp_clean'].notna() &
                    df_hisp['hisp_clean'] > 0 &
                    (df_hisp['STATEFIP'] == 25) &
                    (df_hisp['bpl_binary'] == 1)
                    ]

#making a new df that counts the number of respondents in each hispanic  category in Massachusetts
df_hisp_MA_sum = (
    df_hisp_MA
    .groupby(['hisp_clean'])
    .size()
    .reset_index(name='count')
)

#renaming hisp_clean categories to be strings
mapping = {
    1: 'Mexican',
    2: 'Puerto Rican',
    3: 'Cuban',
    4: 'Dominican',
    5: 'Salvadoran',
    6: 'Central American (except Salvadoran)',
    7: 'South American',
    8: 'Other Hispanic',
}

df_MA_sum['hisp_clean'] = df_MA_sum['hisp_clean'].map(mapping)

df_MA_sum

                             hisp_clean  count
0                               Mexican    170
1                          Puerto Rican   1125
2                                 Cuban     34
3                             Dominican    473
4                            Salvadoran    184
5  Central American (except Salvadoran)    191
6                        South American    305
7                        Other Hispanic    959