In [42]:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ALEJANDRO MELGUIZO
# DATE: 8/18/2026
# TOPIC: new file to filter and clean data for analysis
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk

In [25]:
#set working directory
os.chdir("C:/Users/A.Melguizo001/Downloads/Immig, Wages, Latinos")

In [50]:
#defining data frames
df_1 = pd.read_csv('gaston_df_v2.csv')
df_hisp = df_1.copy()

#dropping hisp_clean to re-categorize
df_hisp = df_hisp.drop(columns= ['hisp_clean'])

In [51]:
#re-categorizing hispanic category
hispan_cases = [
    (df_hisp['HISPAN'] == 0, 0),
    ((df_hisp['HISPAN'] >= 100) & (df_hisp['HISPAN'] <= 109), 1),
    (df_hisp['HISPAN'] == 200, 2),
    (df_hisp['HISPAN'] == 300, 3), 
    (df_hisp['HISPAN'] == 400, 4),
    (df_hisp['HISPAN'] == 500, 5),
    ((df_hisp['HISPAN'] == 610) | (df_hisp['HISPAN'] == 611), 6),
    (df_hisp['HISPAN'] == 612, 7),
    (df_hisp['HISPAN'] == 600, 8),
    ((df_hisp['HISPAN'].isna()) | (df_hisp['HISPAN'] == 902), 9)
]

df_hisp['hisp_clean'] = (
    pd.Series(np.nan, index = df_hisp.index)
    .case_when(hispan_cases)
    .fillna(9)
    .astype(int)
)

df_hisp

,YEAR,REGION,STATEFIP,AGE,SEX,RACE,BPL,YRIMMIG,CITIZEN,NATIVITY,...,bpl_detail,nativity_clean,educ_clean,region_clean,sex_clean,citizen_clean,empstat_clean,incwage_clean,inctot_clean,hisp_clean
0,2000,11,23,51,2,100,45300,1,3,5,...,4.0,5.0,4,1,1,1,1,44600.0,78644.000,0
1,2000,11,23,41,1,100,41400,3,4,5,...,4.0,5.0,2,1,0,2,1,37500.0,37525.000,0
2,2000,11,23,59,1,100,41100,3,4,5,...,4.0,5.0,0,1,0,2,1,23000.0,23025.000,0
3,2000,11,23,55,2,100,15000,3,4,5,...,0.0,5.0,1,1,1,2,1,4860.0,5009.000,0
4,2000,11,23,59,1,100,11000,5,2,5,...,0.0,5.0,2,1,0,1,1,44000.0,44000.000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415916,2025,42,15,58,2,651,51500,38,4,5,...,5.0,5.0,2,4,1,2,1,19647.0,20733.426,0
415917,2025,42,15,61,2,651,51500,7,4,5,...,5.0,5.0,1,4,1,2,1,29736.0,29736.000,0
415918,2025,42,15,36,2,651,50000,41,5,5,...,5.0,5.0,2,4,1,0,1,8549.1,8549.631,0
415919,2025,42,15,55,2,651,51500,9,4,5,...,5.0,5.0,2,4,1,2,3,0.0,19010.331,0
415920,2025,42,15,57,1,652,10000,11,2,5,...,0.0,5.0,3,4,0,1,3,0.0,29433.861,0

In [53]:
#filter to only include:
#hispanic respondents, non-PRicans, Massachusetts respondents
df_hisp_MA = df_hisp[(df_hisp['hisp_clean'] > 0) &
                    (df_hisp['STATEFIP'] == 25) &
                    (df_hisp['bpl_binary'] == 1) &
                    (df_hisp['AGEATIMMIG'].notna())
                    ]

#making a new df that counts the number of respondents in each hispanic  category in Massachusetts
df_hisp_MA_sum = (
    df_hisp_MA
    .groupby(['hisp_clean'])
    .size()
    .reset_index(name='count')
)

#renaming hisp_clean categories to be strings
mapping = {
    1: 'Mexican',
    2: 'Puerto Rican',
    3: 'Cuban',
    4: 'Dominican',
    5: 'Salvadoran',
    6: 'Central American (except Salvadoran)',
    7: 'South American',
    8: 'Other Hispanic',
}

df_hisp_MA_sum['hisp_clean'] = df_hisp_MA_sum['hisp_clean'].map(mapping)

df_hisp_MA_sum

                             hisp_clean  count
0                               Mexican    183
1                          Puerto Rican     44
2                                 Cuban     33
3                             Dominican    471
4                            Salvadoran    184
5  Central American (except Salvadoran)    994
6                        South American    305
7                        Other Hispanic    121

In [54]:
df_hisp_MA

,YEAR,REGION,STATEFIP,AGE,SEX,RACE,BPL,YRIMMIG,CITIZEN,NATIVITY,...,bpl_detail,nativity_clean,educ_clean,region_clean,sex_clean,citizen_clean,empstat_clean,incwage_clean,inctot_clean,hisp_clean
95,2000,11,25,49,2,100,21070,3,3,5,...,1.0,5.0,1,1,1,1,3,0.0,2988.000,2
101,2000,11,25,43,2,100,26010,9,5,5,...,2.0,5.0,0,1,1,0,1,11486.0,11486.000,8
102,2000,11,25,44,1,100,26010,9,5,5,...,2.0,5.0,0,1,0,0,1,0.0,38000.000,8
105,2000,11,25,37,2,100,26010,10,5,5,...,2.0,5.0,1,1,1,0,1,10000.0,10000.000,6
108,2000,11,25,33,2,100,26010,11,5,5,...,2.0,5.0,0,1,1,0,3,0.0,10704.000,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402224,2025,11,25,37,1,300,26010,32,4,5,...,2.0,5.0,2,1,0,2,1,41949.0,43606.251,4
402225,2025,11,25,40,2,300,30025,35,4,5,...,3.0,5.0,4,1,1,2,1,74340.0,75004.281,7
402237,2025,11,25,56,1,801,26010,61,5,5,...,2.0,5.0,1,1,0,0,1,31010.4,31010.400,4
402243,2025,11,25,43,1,100,21040,26,5,5,...,1.0,5.0,0,1,0,0,1,45135.0,50445.000,6
402244,2025,11,25,36,2,100,21040,38,5,5,...,1.0,5.0,0,1,1,0,1,10089.0,10089.000,6